language: python
group: travis_latest
dist: xenial

python:
- 3.7

addons:
  apt:
    packages: ffmpeg

install: pip install -r requirements.txt

script:
- flake8 --extend-ignore=W,E1,E2,E3,E5
- pytest

